spring.application.name=BridgifyProject

# =========================
# DATABASE (MySQL)
# =========================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bridgify?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1111

# =========================
# MYBATIS
# =========================
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.cloud.domain.entity

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================
# API KEYS
# =========================
api.alphavantage.key=HGVA1VC2D7N65L5I
api.exchangerate.key=5eeac867951026d79ff3895d

server.port=8080